Repository vinigracindo/mercado-fresco-stranger-strings, pull requests merged in 2022-06, with the labels that each got.

#4 WIP/feature-requirement2-warehouse
  internal/domains/warehouse/WarehouseModel.go
  internal/domains/warehouse/WarehouseRepository.go
Labels: enhancement, WIP

#7 Feature/requirement3/section1-create-get
  cmd/server/controllers/SectionController.go
  cmd/server/main.go
  internal/domains/section/SectionRepository.go
  internal/domains/section/SectionService.go
Labels: enhancement, to review

#31 Feature/employees - #5 - Delete employee
  cmd/server/controllers/EmployeeController.go
  cmd/server/main.go
  internal/domains/employees/EmployeeModel.go
  internal/domains/employees/EmployeeRepository.go
  internal/domains/employees/EmployeeService.go
  internal/domains/warehouse/WarehouseModel.go
  internal/domains/warehouse/WarehouseRepository.go
Labels: enhancement, to review

#29 Feature/product-5-create-delete
  cmd/server/controllers/ProductController.go
  cmd/server/main.go
  go.sum
  internal/domains/product/ProductModel.go
  internal/domains/product/ProductRepository.go
  internal/domains/product/ProductService.go
  internal/domains/warehouse/WarehouseModel.go
  internal/domains/warehouse/WarehouseRepository.go
Labels: enhancement, to review

#9 Feature/requirement3/section1/create-getById-route
  cmd/server/controllers/SectionController.go
  cmd/server/main.go
  internal/domains/section/SectionRepository.go
  internal/domains/section/SectionService.go
Labels: enhancement, to review

#33 Feature/warehouse 5 update
  .gitignore
  cmd/server/controllers/WarehouseController.go
  cmd/server/main.go
  go.mod
  go.sum
  internal/domains/warehouse/WarehouseModel.go
  internal/domains/warehouse/WarehouseRepository.go
  internal/domains/warehouse/WarehouseService.go
Labels: enhancement, to review

#19 WIP/Feature/requirement3/section1/create-postSection-route
  cmd/server/controllers/SectionController.go
  cmd/server/main.go
  internal/domains/section/SectionRepository.go
  internal/domains/section/SectionService.go
Labels: enhancement, to review

#21 Feature/requirement3/section1/create-patch-route
  cmd/server/controllers/SectionController.go
  cmd/server/main.go
  internal/domains/section/SectionRepository.go
  internal/domains/section/SectionService.go
Labels: enhancement, to review

#17 Feature/req6 buyer getall
  cmd/server/main.go
  internal/domains/buyer/BuyerService.go
Labels: enhancement, to review

#16 Feature/req6 buyer post
  cmd/server/controllers/BuyerController.go
  internal/domains/buyer/BuyerRepository.go
Labels: enhancement, to review

#22 Feature/requirement3/section5/create-delete-route
  cmd/server/controllers/SectionController.go
  cmd/server/main.go
  internal/domains/section/SectionRepository.go
  internal/domains/section/SectionService.go
Labels: enhancement, to review

#1 feature-requirement3-section
  cmd/server/controllers/SectionController.go
  cmd/server/main.go
  internal/domains/section/SectionModel.go
  internal/domains/section/SectionRepository.go
  internal/domains/section/SectionService.go
Labels: enhancement, to review

#2 feature-requirement5-employee
  cmd/server/controllers/EmployeeController.go
  cmd/server/controllers/SectionController.go
  cmd/server/main.go
  internal/domains/employees/EmployeeModel.go
  internal/domains/employees/EmployeeRepository.go
  internal/domains/employees/EmployeeService.go
Labels: enhancement, to review

#3 feature-requirement4-product
  .gitignore
  cmd/server/controllers/ProductController.go
  cmd/server/main.go
  go.sum
  internal/domains/product/ProductModel.go
  internal/domains/product/ProductRepository.go
  internal/domains/product/ProductService.go
Labels: enhancement, to review

#34 feature-requirement-2-warehouse
  .gitignore
  cmd/server/controllers/WarehouseController.go
  cmd/server/main.go
  go.mod
  go.sum
  internal/domains/warehouse/WarehouseModel.go
  internal/domains/warehouse/WarehouseRepository.go
  internal/domains/warehouse/WarehouseService.go
Labels: enhancement, to review

#5 feature-requirement1-seller
  cmd/server/controllers/SellerController.go
  cmd/server/main.go
  internal/domains/seller/SellerModel.go
  internal/domains/seller/SellerRepository.go
  internal/domains/seller/sellerService.go
  internal/domains/warehouse/WarehouseModel.go
  internal/domains/warehouse/WarehouseRepository.go
Labels: enhancement, to review

#6 feature-requirement6-buyer
  cmd/server/controllers/BuyerController.go
  cmd/server/main.go
  internal/domains/buyer/BuyerModel.go
  internal/domains/buyer/BuyerRepository.go
  internal/domains/buyer/BuyerService.go
Labels: enhancement, to review

#38 fix conflict controllers names
  cmd/server/controllers/BuyerController.go
  cmd/server/controllers/ProductController.go
  cmd/server/controllers/SectionController.go
  cmd/server/controllers/WarehouseController.go
Labels: bug

#39 Proposta de melhoria no arquivo main.go
  README.md
  cmd/server/server.go
  go.mod
  go.sum
  main.go
Labels: enhancement

#44 Add swagger for warehouse routes
  cmd/server/controllers/WarehouseController.go
  internal/domains/warehouse/WarehouseService.go
Labels: documentation

#50 Feature/Refactoring of the erros and responses message
  cmd/server/controllers/WarehouseController.go
Labels: enhancement, refactor

#49 feature/requirement3/chaging-response-and-errors
  cmd/server/controllers/SectionController.go
Labels: refactor

#54 Buyer - Refactoring of the erros and responses message
  cmd/server/controllers/BuyerController.go
Labels: refactor

#55 buyer-tests
  cmd/server/controllers/BuyerController.go
  cmd/server/controllers/buyer_test.go
  cmd/server/server.go
  go.mod
  go.sum
  internal/domains/buyer/BuyerModel.go
  internal/domains/buyer/BuyerRepository.go
  internal/domains/buyer/BuyerService.go
  internal/domains/buyer/mocks/Repository.go
  internal/domains/buyer/mocks/Service.go
  internal/domains/buyer/service_test.go
Labels: enhancement, need-review

#56 Feature/employee-service-tests
  .pre-commit-config.yaml
  cmd/server/controllers/EmployeeController.go
  cmd/server/controllers/employee_test.go
  cmd/server/server.go
  go.mod
  internal/domains/employees/EmployeeModel.go
  internal/domains/employees/EmployeeRepository.go
  internal/domains/employees/EmployeeService.go
  internal/domains/employees/errors.go
  internal/domains/employees/mocks/Repository.go
  internal/domains/employees/mocks/Service.go
  internal/domains/employees/service_test.go
Labels: enhancement, need-review

#59 Feature/requirement4 product tests - service e controller
  cmd/server/controllers/ProductController.go
  cmd/server/controllers/product_test.go
  go.mod
  internal/domains/product/ProductModel.go
  internal/domains/product/ProductRepository.go
  internal/domains/product/ProductService.go
  internal/domains/product/mocks/ProductRepository.go
  internal/domains/product/mocks/ProductService.go
  internal/domains/product/service_test.go
Labels: enhancement, need-review

#57 Feature: requirement 02 warehouses test
  cmd/server/controllers/WarehouseController.go
  cmd/server/controllers/warehouse_test.go
  go.mod
  internal/domains/warehouse/WarehouseModel.go
  internal/domains/warehouse/WarehouseRepository.go
  internal/domains/warehouse/WarehouseService.go
  internal/domains/warehouse/mocks/Repository.go
  internal/domains/warehouse/mocks/Service.go
  internal/domains/warehouse/service_test.go
Labels: enhancement, need-review

#60 Feature/requirement1 seller tests
  cmd/server/controllers/SellerController.go
  cmd/server/controllers/seller_test.go
  cmd/server/server.go
  internal/domains/seller/SellerModel.go
  internal/domains/seller/SellerRepository.go
  internal/domains/seller/mocks/Repository.go
  internal/domains/seller/mocks/Service.go
  internal/domains/seller/sellerService.go
  internal/domains/seller/service_test.go
Labels: need-review

#61 [Refactor] Improvement proposal
  cmd/server/controllers/Section_test.go
  cmd/server/controllers/SellerController.go
  cmd/server/controllers/WarehouseController.go
  cmd/server/controllers/buyer_test.go
  cmd/server/controllers/employee_test.go
  cmd/server/controllers/product_test.go
  cmd/server/controllers/seller_test.go
  cmd/server/controllers/warehouse_test.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.sum
  pkg/testutil/server.go
Labels: improvement

#73 refactor folder struct/routes - buyer
  cmd/server/controllers/buyer/BuyerController.go
  cmd/server/controllers/buyer/buyer_test.go
  cmd/server/routes/BuyerRoutes.go
  cmd/server/server.go
  internal/buyer/domain/BuyerModel.go
  internal/buyer/domain/mocks/BuyerRepository.go
  internal/buyer/domain/mocks/BuyerService.go
  internal/buyer/repository/BuyerRepository.go
  internal/buyer/service/BuyerService.go
  internal/buyer/service/service_test.go
Labels: need-review, refactor

#68 Refactor employees folder/files structure
  cmd/server/controllers/employees/EmployeeController.go
  cmd/server/controllers/employees/employee_test.go
  cmd/server/routes/EmployeeRoutes.go
  cmd/server/server.go
  internal/employees/domain/EmployeeModel.go
  internal/employees/domain/errors.go
  internal/employees/domain/mocks/EmployeeRepository.go
  internal/employees/domain/mocks/EmployeeService.go
  internal/employees/repository/EmployeeRepository.go
  internal/employees/service/EmployeeService.go
  internal/employees/service/service_test.go
Labels: need-review, refactor
